### ISSUE TITLE
Add disabled status message to include external config info if present

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#44]

**Comment by cprafullchandra** [comment]
@cglewis, here are my initial thoughts.
- [ ] I'll add another function to get_status to take disabled images and check if those images have been externally configured in core.template
- [ ] I'll add the necessary argparse code to deal with the new function
- [ ] In menu_launcher, I'll call the new function and throw it into a new menu called Externally Configured
- [ ] *Debating* - Modify disabled images/containers in menu_launcher before they are put into the menu so that they have an extra ` - externally configured @ ip `

**Comment by cglewis** [comment]
that sounds like a reasonable plan forward.
