### ISSUE TITLE
when vent starts, it should detect any images/containers for vent and update the manifest

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#556]

**Comment by Jeff-Wang93** [comment]
Current problems with this issue:
1) Assuming we dont have the `.internals` folder, there is no way to fill in the `service`, `setting`, or `docker` portion of the `plugin_manifest` meaning Vent can't use the image. 
2) Given just a docker image's attrs, we cannot search the `plugin_manifest` for that specific image to see if it already exists within the manifest. Also, with that in mind, we cannot write a section name either. 
3) Adding more labels inside `vent/api/plugins.py` will not fix the problem because this file is not run at Vent start.
