### ISSUE TITLE
updating/rebuilding plugins doesn't seem to be working

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#603]

**Comment by cglewis** [comment]
depends on #672 for testing

**Comment by Jeff-Wang93** [comment]
**Current thoughts:**
1. We could re-add the image. This way, a fresh section for `plugin_manifest.cfg` is written with all correct information. The problem is with private repos. There's no way to grab the password nor is it smart to store it in some file. 

2. We could just update `plugin_manifest.cfg`. Problems are that we don't have all the information. We can't update `version`, `image_name`, and `last_updated`. `plugin_helper.checkout()` returns an abridged commit message. It will return something akin to `(True, 'HEAD is now at b89b7fe some-commit-message')  

**Other scenarios:** 
- What if a user changes `grafana` to `Grafana`? Should those be treated separately?
- What if you update a plugin that no longer exists? Eg: `grafana` is deleted from `vent-plugins`. What will update do? Should it delete `grafana` from the manifest?

**Comment by cglewis** [comment]
basics seem to be working for now. closing. can reopen in the future to address other scenarios
