### ISSUE TITLE
file paths from file drop that need escaping (space, backslash, colon, etc.) don't work

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#643]

**Comment by Jeff-Wang93** [comment]
Here's a sample error message that appears:
`ERROR - failed to start cyberreboot-vent-rq-worker-master because: 500 Server Error: Internal Server Error ("create ~/Documents: "~/Documents" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path")`

**Comment by cglewis** [comment]
related to #694
