### ISSUE TITLE
file paths for file_drop need to be absolute paths

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent#694]

**Comment by Jeff-Wang93** [comment]
Here's a sample error message that appears:
`ERROR - failed to start cyberreboot-vent-rq-worker-master because: 500 Server Error: Internal Server Error ("create ~/Documents: "~/Documents" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path")`

From my logs, `rq-worker-master`, `network-tap-master`, and `file-drop-master` fail to start with the exact same error.
